### ISSUE TITLE
Ignoring some fields on serializing object

### ISSUE THREAD

**Issue by cometkim** [DZakh/rescript-struct#28]
For type `t` which has some functions, won't be serialized.

```res
module Wallet = {
  type id = WalletId(string)
  type t = {
    balance: int,
    id: id,
    transfer: Transaction.t => Js.Promise2.t<unit>,
  }
}
```

I can transform the `transfer` field into meaningless value, but how can I totally ignore the field when serializing? (and re-init when deserializing? I guess)

**Comment by DZakh** [comment]
Could you show how you do it without rescript-struct?

**Comment by DZakh** [comment]
And a small tip, you can use `promise` instead of `Js.Promise2.t`

**Comment by cometkim** [comment]
The example is from reason-nact, which is I'm trying to migrate to ReScript with this library.

https://github.com/ncthbrt/reason-nact/blob/master/examples/wallet.res#L11-L40

**Comment by DZakh** [comment]
https://github.com/ncthbrt/reason-nact/blob/13023a0ec44fb6a7fd0f054e76bc0a97d26973c6/examples/wallet.res#L37

I see. If the line should be `balance: field("balance", int, json)` instead, then it's possible with `rescript-struct` using transform:

```rescript
let makeStateStruct = (~parent) => {
  S.object(o =>
    {
      "walletId": Wallet.WalletId(o->S.field("id", S.string())),
      "balance": o->S.field("balance", S.int()),
    }
  )->S.transform(
    ~parser=(tmpWallet): Wallet.t => {
      id: tmpWallet["walletId"],
      balance: tmpWallet["balance"],
      transactions: transactionsQuery(parent, tmpWallet["walletId"]),
    },
    ~serializer=wallet =>
      {
        "walletId": wallet.id,
        "balance": wallet.balance,
      },
    (),
  )
}
```

**Comment by DZakh** [comment]
But I'd store only wallet-related data in the `Wallet.t`. And instead of attaching methods to it, I'd have a function that accepts wallet as a first argument (more ReScript-ish way):

```
let loadWalletTransactions = (wallet, ~parent) => {
  let WalletId(walletId) = wallet.id
  Nact.persistentQuery(
    ~key="wallet" ++ walletId,
    parent,
    (state, msg) =>
      switch msg {
      | #Transaction(t) => Js.Promise.resolve(list{t, ...state})
      | _ => Js.Promise.resolve(state)
      },
    list{},
  )
}
```

**Comment by DZakh** [comment]
And I've already shown it in another issue, but you can extend `rescript-struct` to make it more convenient to work with `Nact`:

```rescript
// S.res
include ReScriptStruct.S

let toNactDecoder = (struct: t<'a>): Nact.decoder<'a> = parseOrRaiseWith
let toNactEncoder = (struct: t<'a>): Nact.encoder<'a> = serialzeOrRaiseWith->Obj.magic
```

> In the next versions, I'll add something like `serializeOrRaiseToJsonWith` so it's possible to use without `Obj.magic`, but it should be fine this way now.
