### ISSUE TITLE
Missing dependency S-RescriptStruct in search path when package-specs: modules: es6-global

### ISSUE THREAD

**Issue by kiuKisas** [DZakh/rescript-struct#33]
Well first, I want to say thank you for your work, really enjoy using rescript-struct :)
I need to export my rescript code in es6 format, so I tried to change my package-specs in bsconfig.json,
but I got this error from my IDE:
```
Missing dependency S-RescriptStruct in search path
```
Also have this flag in my bsconfig: `  "bsc-flags": ["-open ReScriptStruct"]
`
Not sure why and how it can be fix though, I guess I can copy `S.res` in my project but I would prefer avoid that.

Any idea ?

**Comment by DZakh** [comment]
Great to hear that the problem resolved 😊

**Comment by jderochervlk** [comment]
I am also seeing this problem on my project: https://github.com/jderochervlk/family-calendar

With this config I have no issues.
```
  "package-specs": [
    {
      "module": "commonjs", 
      "in-source": true
    }
  ],
  ```

If I change this to `es6` I get the missing dependency error. I've deleted the build lib folder and re-tried running a Rescript build and I still get the error. `es6-global` also causes this error.

**Comment by DZakh** [comment]
Try to run `rescript build -with-deps`
