### ISSUE TITLE
Difficulty with discriminated union

### ISSUE THREAD

**Issue by jmagaram** [DZakh/rescript-struct#37]
The docs/samples on your home page are pretty good but I couldn't figure out the discriminated union. I looked at the tests and found the shapes example, but all the cases have data. I'm getting a runtime problem in my code about this and can't figure it out. The syntax is kind of weird with the `let _` - why is that being ignored? I'm getting the error `The object defention contains fields that weren't registered.` and I think it has to do with this code.

```
type t = Forgot | Remembered({mistakes: bool, elapsedMs: int})

let struct = {
  let forgot = S.object(o => {
    let _ = o->S.field("kind", S.literal(String("forgot")))
    Forgot
  })

  let remembered = S.object(o => {
    let _ = o->S.field("kind", S.literal(String("remembered")))
    Remembered({
      mistakes: o->S.field("mistakes", S.bool()),
      elapsedMs: o->S.field("elapsedMs", S.int()->S.Int.min(1)),
    })
  })
  S.union([forgot, remembered])
}
```

**Comment by jmagaram** [comment]
I also see there is something called `S.discriminant` vs `S.field`. Confusing.

**Comment by jmagaram** [comment]
Ok the test you wrote uses `S.field` and your documentation shows `S.field` and that code fails for me. But `S.discriminant` works. So I must have an out-of-date version? I'm using `^3.1.0`

**Comment by DZakh** [comment]
You're looking at the documentation for the master branch. It will be released in 1-3 weeks. For version `^3.1.0` you need to use `S.discriminant`, sorry. 
https://github.com/DZakh/rescript-struct/blob/v3.1.0/README.md#transform-to-a-variant

**Comment by DZakh** [comment]
`rescript-struct@4.0.0` is now published. You can find the release notes here: https://github.com/DZakh/rescript-struct/releases/tag/v4.0.0
