### ISSUE TITLE
Intersection Types

### ISSUE THREAD

**Issue by justin0mcateer** [DZakh/rescript-struct#60]
Apologies in advance if this is an ignorant question, I am not really very familiar with Rescript, I am trying out using the library via the TypeScript API.

Is there anyway to re-use parts of the schema, which are not themselves fields, eg a group of fields? In my mind this would be analogous to a mix-in or how you might use 'intersection' algebraic types in TypeScript

**Comment by DZakh** [comment]
Could you provide an example using https://github.com/colinhacks/zod. Even if it's not possible with the current API, I can add support for this in the next version.

**Comment by DZakh** [comment]
Are you referring to something like this? https://github.com/colinhacks/zod#intersections

**Comment by justin0mcateer** [comment]
Yes, precisely.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by DZakh** [comment]
I'll add it in the V5.1

**Comment by DZakh** [comment]
I've added it as [`S.merge`](https://github.com/DZakh/rescript-struct/blob/v5.1.0/docs/js-usage.md#merge) in the [V5.1](https://github.com/DZakh/rescript-struct/releases/tag/v5.1.0) release. Let me know if you need anything else. Starting from V5.1 I've decided to make JS/TS API a legit target for rescript-struct.
