### ISSUE TITLE
Accessing type-specific refinements from TS?

### ISSUE THREAD

**Issue by denizdogan** [DZakh/rescript-struct#61]
I cannot figure out how to access any type-specific refinements from TypeScript.

<img width="469" alt="Screenshot 2023-07-07 at 18 08 10" src="https://github.com/DZakh/rescript-struct/assets/50928/cfb2ac46-45a5-4f1f-be76-156f57e51704">

What am I doing wrong here? It looks like it's simply not being compiled into the d.ts at all.

**Comment by DZakh** [comment]
I haven't added support for them yet. I postponed it because didn't expect much ts users. Let me know how urgent it is for. Depending on it I'll plan when to do the next release with type-specific refinements for ts.

**Comment by denizdogan** [comment]
Oh, I see. Well, it wasn't obvious to me that this library could even be used with TypeScript in the first place, because the docs didn't mention anything about it. 😄  It's definitely not urgent, but I am very interested in using this for a project I'm working on.

**Comment by DZakh** [comment]
I've decided to change the TS API from zod-like to valibod-like (tree-shakable), so it became easier to add. They are in master now https://github.com/DZakh/rescript-struct/commit/aaaccebcdb87ddd04b86b491da0569e7e7bc566c.
I'll try to finish v5 next week and make a release.
